/**
 * Brava demo config — the portfolio demo at /templates/brava/demo.
 * Placeholder brand and copy; images from picsum seeds. A client project gets
 * a `site.config.ts` with the same shape (generated by scripts/new-client.mjs).
 */
import { defineBrava } from './schema';

import hero1 from './assets/demo/hero-1.jpg';
import hero2 from './assets/demo/hero-2.jpg';
import hero3 from './assets/demo/hero-3.jpg';
import product1 from './assets/demo/product-1.jpg';
import product2 from './assets/demo/product-2.jpg';
import product3 from './assets/demo/product-3.jpg';
import product4 from './assets/demo/product-4.jpg';
import product5 from './assets/demo/product-5.jpg';
import product6 from './assets/demo/product-6.jpg';
import lookbook1 from './assets/demo/lookbook-1.jpg';
import lookbook2 from './assets/demo/lookbook-2.jpg';
import lookbook3 from './assets/demo/lookbook-3.jpg';
import lookbook4 from './assets/demo/lookbook-4.jpg';

export default defineBrava({
	brand: {
		name: 'BRAVA',
		tagline: 'Small batches. Made on purpose.',
		logo: null,
		locale: 'en',
	},
	theme: {
		accent: '#059669',
		/* light tint of the accent — used for highlights on the dark newsletter block */
		accent2: '#6ee7b7',
		bg: '#f7fbf9',
		ink: '#0e1a14',
		radius: 12,
	},
	seo: {
		title: 'Brava Drop: template demo',
		description: 'Demo of the Brava template: limited-drop e-commerce landing by Fab Bahiense. Placeholder data.',
		canonical: 'https://www.fabbahiense.dev/templates/brava/demo',
		ogImage: hero1,
	},
	contact: {
		form: {
			provider: 'none',
			successMessage: "You're on the list. See you next drop.",
		},
	},
	analytics: {},
	legal: {
		lines: ['© 2026 Brava · Made in Brazil, shipped from São Paulo.'],
	},
	nav: [
		{ label: 'Shop', href: '#shop' },
		{ label: 'Lookbook', href: '#lookbook' },
		{ label: 'Story', href: '#story' },
	],

	ticker: {
		messages: [
			'Drop 03 / Verão · live until September 30',
			'free shipping over R$ 300',
			'pre-orders ship in 7 days',
			'only 250 pieces per drop',
		],
	},

	topbar: {
		brandHref: '#top',
		links: [
			{ label: 'Search', href: '#' },
			{ label: 'Account', href: '#' },
		],
		cart: { show: true, label: 'Cart', href: '#', count: 2 },
	},

	drop: {
		endsAt: '2026-09-30T23:59:59-03:00',
		countdownLabel: 'Time until drop ends',
		units: { days: 'days', hours: 'hrs', minutes: 'min', seconds: 'sec' },
		ended: 'This drop has ended. Sign up below to hear about the next one.',
	},

	hero: {
		eyebrow: '// Drop 03 / Verão · 250 pieces · live now',
		lines: ['The summer', '**that ends**', '==too fast.=='],
		sub: "Six pieces, made in Brazil, shipped worldwide. When they're gone, they're gone. We don't restock.",
		cta: { label: 'Shop the drop →', href: '#shop' },
		tiles: [
			{ image: hero1, alt: 'Model wearing the Vento Tee on the beach at Búzios' },
			{ image: hero2, alt: 'Close-up of the Maré Hoodie embroidery' },
			{ image: hero3, alt: 'Costa Cap and Sol Tote on the sand', tint: '#fbe07e' },
		],
	},

	shop: {
		eyebrow: '// The drop · 06 pieces',
		title: 'Take your pick.',
		soldLabel: 'SOLD OUT',
		products: [
			{ n: '001', name: 'Vento Tee', price: 'R$ 189', tag: 'OG', image: product1, alt: 'Vento Tee, off-white' },
			{ n: '002', name: 'Maré Hoodie', price: 'R$ 459', tag: 'NEW', image: product2, alt: 'Maré Hoodie, deep green', tint: '#fbe07e' },
			{ n: '003', name: 'Costa Cap', price: 'R$ 149', image: product3, alt: 'Costa Cap, sand', tint: '#bae6fd' },
			{ n: '004', name: 'Sol Tote', price: 'R$ 119', tag: 'LAST', image: product4, alt: 'Sol Tote, natural canvas', tint: '#f9c4e3' },
			{ n: '005', name: 'Brisa Crewneck', price: 'R$ 389', sold: true, image: product5, alt: 'Brisa Crewneck, grey', tint: '#d1d5db' },
			{ n: '006', name: 'Ouro Socks', price: 'R$ 79', image: product6, alt: 'Ouro Socks, pair', tint: '#f59e0b' },
		],
	},

	lookbook: {
		title: 'Lookbook',
		eyebrow: '// Lookbook',
		caption: 'Shot in Búzios, March 2026. Photography by Maré Studio.',
		tiles: [
			{ image: lookbook1, alt: 'Full look on the rocks at Praia Brava' },
			{ image: lookbook2, alt: 'Maré Hoodie, back view' },
			{ image: lookbook3, alt: 'Sol Tote detail' },
			{ image: lookbook4, alt: 'The six pieces laid out on the sand' },
		],
	},

	story: {
		eyebrow: '// The story',
		title: 'Small batches. ==Made on purpose.==',
		paragraphs: [
			'Brava is a Brazilian label run by two friends. We design, sample and stitch each piece in Rio, then ship from a single warehouse in São Paulo.',
			"We release four drops a year, 200 to 300 pieces each. No restocks, no seasons, no Black Friday. When a piece sells out it's gone, and we move on to the next thing.",
		],
		link: { label: 'Read more →', href: '#' },
	},

	newsletter: {
		title: 'Be first ==next drop.==',
		sub: 'One email per drop. Never marketing, just the link, the date, and a thank you.',
		email: { label: 'Your email', placeholder: 'you@email.com' },
		cta: 'Notify me',
	},

	footer: {
		columns: [
			{
				h: 'Shop',
				links: [
					{ label: 'The drop', href: '#shop' },
					{ label: 'Archive', href: '#' },
					{ label: 'Gift cards', href: '#' },
				],
			},
			{
				h: 'Help',
				links: [
					{ label: 'Shipping', href: '#' },
					{ label: 'Returns', href: '#' },
					{ label: 'Size guide', href: '#' },
				],
			},
			{
				h: 'Brava',
				links: [
					{ label: 'Story', href: '#story' },
					{ label: 'Press', href: '#' },
					{ label: 'Contact', href: '#' },
				],
			},
		],
		socials: [
			{ label: 'Instagram', href: '#' },
			{ label: 'TikTok', href: '#' },
		],
		privacyLabel: 'Privacy',
	},
});
